-- generated: 작업 이력 이관 (시트)

-- customers
INSERT INTO customers (id, name) VALUES (1, '황진희');
INSERT INTO customers (id, name) VALUES (2, '이은형');
INSERT INTO customers (id, name) VALUES (3, '양경용');
INSERT INTO customers (id, name) VALUES (4, '원영걸');
INSERT INTO customers (id, name) VALUES (5, '박태정');
INSERT INTO customers (id, name) VALUES (6, '이현숙');
INSERT INTO customers (id, name) VALUES (7, '김용하');
INSERT INTO customers (id, name) VALUES (8, '구현우');
INSERT INTO customers (id, name) VALUES (9, '이해왕');
INSERT INTO customers (id, name) VALUES (10, '홍유미');
INSERT INTO customers (id, name) VALUES (11, '박병진');
INSERT INTO customers (id, name) VALUES (12, '정봉수');
INSERT INTO customers (id, name) VALUES (13, '이정표');
INSERT INTO customers (id, name) VALUES (14, '박주형');
INSERT INTO customers (id, name) VALUES (15, '김용혁');
INSERT INTO customers (id, name) VALUES (16, '김현종');
INSERT INTO customers (id, name) VALUES (17, '노강엽');
INSERT INTO customers (id, name) VALUES (18, '박재현');
INSERT INTO customers (id, name) VALUES (19, '김지빈');
INSERT INTO customers (id, name) VALUES (20, '정은제');
INSERT INTO customers (id, name) VALUES (21, '이용주');
INSERT INTO customers (id, name) VALUES (22, '이가영');
INSERT INTO customers (id, name) VALUES (23, '이영란');
INSERT INTO customers (id, name) VALUES (24, '안광희');
INSERT INTO customers (id, name) VALUES (25, '이재필');
INSERT INTO customers (id, name) VALUES (26, 'Eriko');
INSERT INTO customers (id, name) VALUES (27, '정현기');
INSERT INTO customers (id, name) VALUES (28, '오현희');
INSERT INTO customers (id, name) VALUES (29, '신숙조');
INSERT INTO customers (id, name) VALUES (30, '강성호');
INSERT INTO customers (id, name) VALUES (31, '이주병');
INSERT INTO customers (id, name) VALUES (32, '민지희');
INSERT INTO customers (id, name) VALUES (33, '김영남');
INSERT INTO customers (id, name) VALUES (34, '최인열');
INSERT INTO customers (id, name) VALUES (35, '고은혁');
INSERT INTO customers (id, name) VALUES (36, '조용우');

INSERT OR REPLACE INTO sqlite_sequence (name, seq) VALUES ('customers', 36);

-- rackets
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (1, 1, '윌슨 Blade 100', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (2, 2, '볼클 vostra', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (3, 3, '헤드 Prestige MP L 2023', NULL, 99, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (4, 4, '윌슨 프로스태프 97 v13', NULL, 97, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (5, 5, '윌슨 Blade v8 104', NULL, 104, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (6, 6, '헤드 그래비티 MP L 2023', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (7, 7, '윌슨 Blade v8 98 305g', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (8, 8, '바볼랏 PureDrive', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (9, 8, '윌슨 Blade v8 98 305g', NULL, 98, '18x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (10, 9, '헤드 리퀴드메탈8', NULL, 112, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (11, 2, '헤드 그래비티 MP L 2023', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (12, 10, '프린스 텍스트림 투어 100 270g', NULL, 100, '16x18');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (13, 11, '요넥스 이존 100', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (14, 1, '윌슨 Blade v8 100', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (15, 12, '바볼랏 Aeropro Drive', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (16, 13, '헤드 그래핀 360+ Prestige S 2그립', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (17, 13, '요넥스 이존 285g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (18, 14, '바볼랏 PureAero Rafa Origin 317g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (19, 7, '헤드 Speed 280g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (20, 8, '프로케넥스 K15 260g', NULL, 105, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (21, 15, '프린스 비스트', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (22, 8, '프로케넥스 270g', NULL, 105, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (23, 8, '프로케넥스 315g', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (24, 16, '헤드 그래비티', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (25, 17, '프린스 텍스트림 투어 100 290g 2022', NULL, 100, '16x18');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (26, 17, '요넥스 이존 285g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (27, 18, '헤드 래디컬', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (28, 19, '윌슨 울트라', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (29, 2, '헤드 그래비티 MP L 2023 1그립', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (30, 13, '바볼랏 PureAero', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (31, 20, '헤드 그라핀 터치 Speed mp', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (32, 21, '윌슨 N3 2021', NULL, 113, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (33, 13, '헤드 그래핀 360+ Prestige S 2그립', NULL, 99, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (34, 13, '던롭 CX400', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (35, 22, '윌슨 Clash v3', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (36, 14, '헤드 그래비티 2025', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (37, 8, '바볼랏 Pure Drive 윔블던 2024', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (38, 13, '헤드 그래핀 360+ Prestige S 3그립', NULL, 99, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (39, 23, '윌슨 N3 2021', NULL, 113, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (40, 24, '요넥스 브이코어 300g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (41, 24, '요넥스 이존 260g', NULL, 102, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (42, 25, '바볼랏 AERO G 270g', NULL, 102, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (43, 26, '헤드 익스트림 260', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (44, 25, '바볼랏 퓨어드라이브라이트', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (45, 27, '바볼랏 퓨어 에어로 라파 290g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (46, 13, '헤드 Prestige MP L 2023', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (47, 24, '윌슨 Blade v7 104SW', NULL, 104, '18x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (48, 9, 'Kelly Ti901', NULL, 110, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (49, 8, '바볼랏 Pure Drive 2022', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (50, 28, '바볼랏 Pure Drive EVO Lite', NULL, 104, '16x17');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (51, 29, '바볼랏 퓨어스트라이크', NULL, 102, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (52, 24, '윌슨 SHIFT', NULL, 100, '16x20');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (53, 30, '프린스 텍스트림 투어 100 270g 2023', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (54, 31, '바볼랏 퓨어드라이브 285g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (55, 4, '윌슨 프로스태프 97', NULL, 97, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (56, 13, '헤드 그래핀 360+ Prestige S', NULL, 99, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (57, 13, '헤드 그래핀 터치 Prestige S', NULL, 95, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (58, 24, '테크니화이버 T-fight 305 2022', NULL, 98, '18x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (59, 32, '윌슨 Blade v8 100 265g', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (60, 10, '프린스 텍스트림 투어 100 270g 2023', NULL, 100, '16x18');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (61, 10, '헤드 BOOM MP L 2024', NULL, 100, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (62, 33, '윌슨 Blade v8 104', NULL, 104, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (63, 8, '바볼랏 Pure Drive 2023', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (64, 34, '윌슨 프로스태프 v13', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (65, 34, '윌슨 프로스태프 v12', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (66, 35, '바볼랏 퓨어에어로', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (67, 6, '헤드 EXTREME Lite', NULL, 105, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (68, 13, '헤드 Prestige MP L 2023', NULL, 99, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (69, 24, '테크니화이버 TEMPO 298', NULL, 98, '16x19');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (70, 36, '윌슨 프로스태프 v11 97 ULS', NULL, 97, '18x16');
INSERT INTO rackets (id, customer_id, racket_model, nickname, head_size, string_pattern) VALUES (71, 24, '테크니화이버 TFX1', NULL, 105, '16x19');

INSERT OR REPLACE INTO sqlite_sequence (name, seq) VALUES ('rackets', 71);

-- string_jobs
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (1, 'Focus HEX', 48, NULL, 8.2, 7.5, '2026-09-04', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (2, '헤드 호크 터치', 48, NULL, 8.3, 7.5, '2026-08-29', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (2, '헤드 호크 터치', 48, NULL, 8.3, 7.5, '2026-08-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 52, NULL, 8.3, 7.5, '2026-08-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'RPM Blast', 42, 40, 8.2, 7.5, '2026-07-25', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'RPM Blast', 42, 40, 8.2, 7.5, '2026-07-25', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (5, 'Tour Bite', 48, NULL, 8.3, 7.5, '2026-06-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (2, '헤드 호크 터치', 48, NULL, 8.3, 7.5, '2026-06-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 52, NULL, 8.3, 7.5, '2026-05-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (6, 'RPM Blast', 46, NULL, 8.3, 7.8, '2026-05-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (7, 'Big Hitter', 50, 48, 8.3, 7.5, '2026-05-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (1, 'Tour Bite', 48, NULL, 8.2, 7.5, '2026-05-13', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (8, '알루파워 러프', 46, NULL, 8.3, 7.5, '2026-04-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (9, '알루파워 러프', 46, NULL, 9, 7.7, '2026-04-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (10, 'Black Pearl', 48, 46, 9, 8, '2026-03-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, '헤드 호크 터치', 48, NULL, 8.3, 7.8, '2026-02-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 52, NULL, 8.3, 7.5, '2026-01-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, '헤드 호크 터치', 48, NULL, 8.3, 7.8, '2026-01-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'RPM Blast', 46, 44, 8.2, 7.5, '2026-01-17', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (12, 'Multi-Feel', 56, NULL, 8, 7.3, '2026-01-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (13, 'ENSO PRO', 46, NULL, 8.2, 7.5, '2025-12-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 48, NULL, 8.2, 7.5, '2025-12-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (15, 'Hyper-G soft', 50, NULL, 8.3, 7.5, '2025-11-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (16, 'M: Alupower ,C: Sensus Rotation', 44, NULL, 8.3, 7.5, '2025-10-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (17, 'Toro Toro', 44, NULL, 8.3, 7.5, '2025-10-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (18, 'RPM Rough', 58, NULL, 8.3, 7.5, '2025-10-26', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (7, 'Big Hitter', 50, 48, 8.3, 7.5, '2025-10-26', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (19, 'Big Hitter', 50, 48, 8.3, 7.5, '2025-10-26', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (9, '알루파워 러프', 46, NULL, 9, 7.7, '2025-10-25', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'RPM Blast', 46, 44, 8.1, 7.2, '2025-10-19', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'RPM Blast', 46, 44, 8.1, 7.2, '2025-10-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (9, 'Tour Bite', 46, NULL, 8.9, 7.7, '2025-09-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (20, 'Tour Bite', 46, NULL, 8.2, 7.5, '2025-09-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 48, NULL, 8.2, 7.5, '2025-09-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (21, 'Hyper-G soft', 48, NULL, 8.2, 7.5, '2025-09-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (8, 'MultiFibre', 54, NULL, 8, 7, '2025-07-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (22, 'MultiFibre', 54, NULL, 8, 7.5, '2025-07-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (23, 'MultiFibre', 54, NULL, 8, 7.5, '2025-07-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (24, '', 52, 50, 8.3, 7.8, '2025-07-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 48, NULL, 8.2, 7.5, '2025-07-05', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (25, 'MultiFibre', 56, NULL, 8, 7.3, '2025-06-29', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (26, 'MultiFibre', 56, NULL, 8, 7.3, '2025-06-29', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, '헤드 호크 터치', 48, NULL, 8.3, 7.8, '2025-06-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (27, '듀얼 코티드', 50, NULL, 8.2, 7.5, '2025-06-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (27, '알루파워 바이브', 50, NULL, 8.2, 7.5, '2025-06-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (27, 'Toro Toro', 50, NULL, 8.2, 7.5, '2025-06-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'Ice Code', 45, NULL, 8.1, 7.2, '2025-06-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'Ice Code', 45, NULL, 8.1, 7.2, '2025-06-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (6, 'RPM Blast', 46, NULL, 8.3, 7.8, '2025-06-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (17, 'MultiFibre', 54, NULL, 8, 7.3, '2025-06-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (28, 'Big Hitter', 48, NULL, 8.3, 7.5, '2025-05-26', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (16, 'MultiFibre', 54, NULL, 8, 7.3, '2025-05-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (6, 'RPM Blast', 46, NULL, 8.3, 7.8, '2025-05-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (29, 'Pentagon', 48, NULL, 8.3, 7.8, '2025-05-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (30, 'MultiFibre', 54, NULL, 8, 7.3, '2025-05-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (31, 'Big Hitter', 50, 48, 8.3, 7.5, '2025-05-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (31, 'Big Hitter', 50, 48, 8.3, 7.5, '2025-05-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (19, 'Big Hitter', 50, 48, 8.3, 7.5, '2025-05-17', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (32, 'Focus HEX', 48, NULL, 9, 8, '2025-05-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (17, 'O-Toro', 50, NULL, 8.3, 7.5, '2025-05-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 48, NULL, 8.2, 7.5, '2025-04-27', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 52, NULL, 8.2, 7.5, '2025-04-20', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Focus HEX', 58, NULL, 8.3, 7.5, '2025-04-20', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (17, 'Polytour Drive', 54, NULL, 8.3, 7.5, '2025-04-19', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (30, 'Wasabi Pink', 54, NULL, 8.3, 7.5, '2025-04-19', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (8, 'ENSO PRO', 54, NULL, 8.3, 7.7, '2025-04-13', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (5, 'Tour Bite', 48, NULL, 8.3, 7.5, '2025-04-13', '24년3분기쿠폰 5');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (34, 'Hyper-G soft', 50, NULL, 8.3, 7.5, '2025-04-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (35, 'M: Icecream ,C: 알루파워 러프', 46, 44, 8.3, 7.5, '2025-04-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (15, 'Hyper-G soft', 50, NULL, 8.3, 7.5, '2025-04-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Toro Toro', 54, NULL, 8.3, 7.5, '2025-03-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (36, 'G-Tour3', 58, NULL, 8.3, 7.8, '2025-03-21', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (36, 'G-Tour3', 58, NULL, 8.3, 7.8, '2025-03-21', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'M: VS Touch ,C: 알루파워 러프', 54, 52, 8, 7.2, '2025-03-20', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'M: VS Touch ,C: 알루파워 러프', 54, 52, 8, 7.2, '2025-03-20', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (38, 'Toro Toro', 50, NULL, 8.3, 7.5, '2025-03-15', '부드러워서 텐션 54로 올릴것');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Tour Bite', 54, NULL, 8.3, 7.5, '2025-03-06', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'Multi-Feel', 54, NULL, 8, 7.2, '2025-03-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'Multi-Feel', 54, NULL, 8, 7.2, '2025-03-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'SNAPPER', 54, NULL, 8.3, 7.5, '2025-02-16', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 52, NULL, 8.3, 7.5, '2025-02-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, 'Polytour Pro', 48, NULL, 8.3, 7.8, '2025-02-04', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (39, 'Tour Bite', 40, NULL, 9, 8, '2025-01-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Big Hitter', 52, NULL, 8.3, 7.5, '2025-01-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 52, NULL, 8.3, 7.5, '2025-01-21', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, '알루파워 러프', 44, 42, 8.3, 7.5, '2025-01-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (40, '알루파워 러프', 52, 50, 8.3, 7.5, '2025-01-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (41, '알루파워 러프', 48, NULL, 8.3, 7.5, '2025-01-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (42, 'Black Widow', 45, NULL, 8.3, 7.5, '2025-01-05', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (42, 'Black Widow', 45, NULL, 8.3, 7.7, '2025-01-05', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (32, 'Focus HEX', 48, NULL, 9, 8, '2025-01-02', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (43, 'SNAPPER', 46, NULL, 8.3, 7.5, '2024-12-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (44, 'Black Widow', 45, NULL, 8.3, 7.7, '2024-12-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (32, 'Focus HEX', 48, NULL, 9, 8, '2024-12-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (45, 'Tour Bite', 52, 50, 8.3, 7.5, '2024-11-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Focus HEX', 50, 48, 8.3, 7.5, '2024-11-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (3, 'RPM Blast', 50, NULL, 8.3, 7.5, '2024-11-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (25, 'Multi-Feel', 54, NULL, 8.2, 7.2, '2024-11-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (46, 'CAVIAR', 56, NULL, 8.3, 7.5, '2024-11-09', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (9, 'ENSO PRO', 54, NULL, 8.8, 8, '2024-11-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (41, '알루파워 러프', 52, NULL, 8.3, 7.5, '2024-11-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (40, 'WASABI Pink', 52, NULL, 8.3, 7.5, '2024-11-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (47, 'Black Pearl', 52, NULL, 9.3, 7.8, '2024-11-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (48, 'Hyper-G soft', 48, NULL, 9.3, 8, '2024-11-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (15, 'G-Tour3', 50, NULL, 8.3, 7.5, '2024-10-27', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (46, 'Polytour Pro', 56, NULL, 8.3, 7.5, '2024-10-20', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'IQ HEXA', 48, NULL, 8.1, 7.2, '2024-10-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'IQ HEXA', 48, NULL, 8.1, 7.2, '2024-10-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'ENSO PRO', 54, NULL, 8.2, 7.2, '2024-10-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (46, 'POLY HIGHTEC', 56, NULL, 8.3, 7.5, '2024-10-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (34, 'M-6 PRO', 54, NULL, 8.3, 7.5, '2024-10-18', '추후에는 텐션46');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 50, NULL, 8.2, 7.5, '2024-10-09', '24년1분기쿠폰 19');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (50, 'SNAPPER', 52, NULL, 8.3, 7, '2024-10-01', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (51, 'Focus HEX', 52, NULL, 8.2, 7.5, '2024-09-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'SNAPPER', 54, NULL, 8.2, 7.2, '2024-09-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (38, 'Devil Spin', 48, NULL, 8.3, 7.5, '2024-09-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'M-6 PRO', 48, NULL, 8.2, 7.5, '2024-09-28', '24년1분기쿠폰 16');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (37, 'M: VS Touch ,C: 알루파워 러프', 54, 52, 8.2, 7.2, '2024-09-21', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'Wasabi Pink', 52, NULL, 8.3, 7.5, '2024-09-21', '맨 줄무게: 18.4g');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, 'RPM Blast', 48, NULL, 8.3, 7.8, '2024-09-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, '알루파워 러프', 48, NULL, 8.3, 7.8, '2024-09-08', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (38, 'Wasabi Pink', 52, NULL, 8.3, 7.5, '2024-09-07', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (52, '알루파워 러프', 50, NULL, 8.2, 7.8, '2024-08-31', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'M: VS Touch ,C: 알루파워 러프', 54, 52, 8.2, 7.2, '2024-08-25', '맨 줄무게: 16.9g');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (26, 'SNAPPER', 54, NULL, 8.2, 7.5, '2024-08-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (53, 'Focus HEX', 44, 42, 8.2, 7.5, '2024-08-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (54, 'Focus HEX', 44, 42, 8.2, 7.5, '2024-08-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (53, 'Hyper-G soft', 45, NULL, 8.2, 7.5, '2024-08-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (33, 'SNAPPER', 57, NULL, 8.2, 7.5, '2024-08-17', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (38, 'SUPER TORO', 56, NULL, 8.2, 7.5, '2024-08-17', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (41, '알루파워 러프', 52, NULL, 8.2, 7.5, '2024-08-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (40, '알루파워 러프', 48, NULL, 8.2, 7.5, '2024-08-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (51, 'Focus HEX', 52, NULL, 8.2, 7.5, '2024-08-11', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (55, 'IQ HEXA', 48, NULL, 8.1, 7.2, '2024-08-10', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (4, 'IQ HEXA', 48, NULL, 8.1, 7.2, '2024-08-10', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (56, 'CAVIOR', 50, NULL, 8.2, 7.5, '2024-08-03', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'Multi-Feel', 54, NULL, 8.2, 7.2, '2024-08-02', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (57, 'Velocity MLT', 56, NULL, 8.1, 7.1, '2024-07-28', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (58, 'G-Tour1', 52, NULL, 8.8, 7.5, '2024-07-27', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (59, 'RPM Rough', 46, NULL, 8.3, 7.5, '2024-07-27', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (60, 'Sensus Rotation', 46, NULL, 8.3, 7.3, '2024-07-25', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (61, 'Hyper-G soft', 46, NULL, 8.3, 7.5, '2024-07-25', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'EGG POWER', 54, NULL, 8.3, 7.5, '2024-07-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (58, 'EGG POWER', 52, NULL, 8.8, 7.5, '2024-07-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (11, 'Polytour Pro', 48, NULL, 8.3, 7.8, '2024-07-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (62, 'Tour Bite', 48, NULL, 8.3, 7.5, '2024-07-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (62, 'Tour Bite', 48, NULL, 8.3, 7.5, '2024-07-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (46, 'M: SUPER TORO ,C: ENSO PRO', 56, NULL, 8.3, 7.5, '2024-07-23', '맨 줄무게: 16.6g');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (63, 'Multi-Feel', 54, NULL, 8.3, 7.5, '2024-07-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (64, 'Wasabi Pink', 50, NULL, 8.3, 7.5, '2024-07-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (64, 'Hepta Twist', 50, NULL, 8.3, 7.5, '2024-07-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (65, 'Sensus Rotation', 50, NULL, 8.3, 7.5, '2024-07-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (66, 'RPM Blast', 53, NULL, 8.3, 7.5, '2024-07-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (58, 'Wasabi Pink', 52, NULL, 9, 7.5, '2024-07-14', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (25, 'Multi-Feel', 52, 50, 8.3, 7.3, '2024-06-30', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (32, 'Focus HEX', 48, NULL, 9, 8, '2024-06-30', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (50, 'Hyper-G soft', 48, NULL, 8.3, 6.5, '2024-06-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (67, 'RPM Blast', 46, NULL, 8.3, 7.5, '2024-06-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (32, 'Focus HEX', 48, NULL, 9, 8, '2024-06-24', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (56, 'Wasabi Pink', 56, NULL, 8.3, 7.5, '2024-06-23', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (63, 'Multi-Feel', 54, NULL, 8.3, 7.3, '2024-06-22', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'Velocity MLT', 54, NULL, 8.3, 7.3, '2024-06-22', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (68, 'M: Sensus Rotation ,C: Black Widow', 56, NULL, 8.3, 7.5, '2024-06-22', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (14, 'Tour Bite', 50, NULL, 8.2, 7.5, '2024-06-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (69, 'Hyper-G soft', 50, NULL, 8.2, 7.5, '2024-06-18', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (62, 'Multi-Feel', 48, NULL, 8.5, 8, '2024-06-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (62, 'Multi-Feel', 48, NULL, 8.2, 7.4, '2024-06-15', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (56, 'Hyper-G soft', 56, NULL, 8.2, 7.5, '2024-06-13', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (70, 'Tour Bite', 54, NULL, 9, 7, '2024-06-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (69, 'Sensus Rotation', 50, NULL, 8.2, 7.5, '2024-06-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (71, 'Sensus Rotation', 46, NULL, 8.7, 8, '2024-06-12', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (49, 'Tour Bite', 52, NULL, 8.2, 7.5, '2024-06-02', '');
INSERT INTO string_jobs (racket_id, string_type, tension_main, tension_cross, cut_length_main, cut_length_cross, job_date, memo) VALUES (47, 'Black Pearl', 50, NULL, 9.3, 8, '2024-06-02', '');

